CREATE TABLE CARTOES (
    ID_CARTAO            NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENTE           NUMBER NOT NULL,
    ID_DEPARTAMENTO      NUMBER NOT NULL,
    NUMERO_CARTAO_HASH   VARCHAR2(64 BYTE) NOT NULL,
    LIMITE_CREDITO       NUMBER(12,2) DEFAULT 0,
    STATUS_CARTAO        VARCHAR2(1 BYTE) DEFAULT 'E' NOT NULL,
    DATA_CADASTRO        DATE DEFAULT TO_DATE(TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'), 'DD/MM/YYYY HH24:MI:SS'),
    
    CONSTRAINT UK_CARTAO_HASH           UNIQUE (NUMERO_CARTAO_HASH),
    CONSTRAINT FK_CARTOES_CLIENTE       FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
    CONSTRAINT FK_CARTOES_DEPARTAMENTO  FOREIGN KEY (ID_DEPARTAMENTO) REFERENCES DEPARTAMENTOS(ID_DEPARTAMENTO),
    CONSTRAINT CHK_STATUS_CARTAO        CHECK (STATUS_CARTAO IN ('A', 'B', 'C', 'I', 'E'))
);

--IDX_CARTOES_CLIENTE
CREATE INDEX IDX_CARTOES_CLIENTE    ON CARTOES(ID_CLIENTE);
CREATE INDEX IDX_CARTOES_DEPTO      ON CARTOES(ID_DEPARTAMENTO);
CREATE INDEX IDX_CARTOES_STATUS     ON CARTOES(STATUS_CARTAO);

COMMENT ON TABLE CARTOES IS 'Tabela de controle de cartões de crédito vinculados a clientes e departamentos internos.';

COMMENT ON COLUMN CARTOES.ID_CARTAO           IS 'Código do cartão.';
COMMENT ON COLUMN CARTOES.ID_CLIENTE          IS 'Cliente responsavel pelo cartão.';
COMMENT ON COLUMN CARTOES.ID_DEPARTAMENTO     IS 'Código do departamento do cartão.';
COMMENT ON COLUMN CARTOES.NUMERO_CARTAO_HASH  IS 'Número do cartão criptografado/hash.';
COMMENT ON COLUMN CARTOES.LIMITE_CREDITO      IS 'Valor total de crédito disponível no cartão.';
COMMENT ON COLUMN CARTOES.STATUS_CARTAO       IS 'Status do cartão: A (Ativo), B (Bloqueado), C (Cancelado), I (Inativo), E (Em Análise).';
COMMENT ON COLUMN CARTOES.DATA_CADASTRO       IS 'Data e hora de criação do registro do cartão.';