CREATE TABLE CLIENTES (
    ID_CLIENTE     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOME_FANTASIA  VARCHAR2(100 BYTE) NOT NULL,
    CNPJ           VARCHAR2(14 BYTE) UNIQUE NOT NULL,
    DATA_CADASTRO  DATE DEFAULT TO_DATE(TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'), 'DD/MM/YYYY HH24:MI:SS')
);


CREATE INDEX IDX_CLIENTES_NOME ON CLIENTES(NOME_FANTASIA);
CREATE INDEX IDX_CLIENTES_CNPJ ON CLIENTES(CNPJ);

COMMENT ON TABLE CLIENTES IS 'Tabela de cadastro de clientes que possuem cartões corporativos.';

COMMENT ON COLUMN CLIENTES.ID_CLIENTE     IS 'Código cliente.';
COMMENT ON COLUMN CLIENTES.NOME_FANTASIA  IS 'Nome fantasia do cliente.';
COMMENT ON COLUMN CLIENTES.CNPJ           IS 'Cadastro Nacional da Pessoa Jurídica (14 dígitos numéricos). Deve ser único.';
COMMENT ON COLUMN CLIENTES.DATA_CADASTRO  IS 'Data e hora de criação do registro do cliente.';