CREATE TABLE DEPARTAMENTOS (
    ID_DEPARTAMENTO    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENTE         NUMBER NOT NULL,
    NOME_DEPARTAMENTO  VARCHAR2(100 BYTE) NOT NULL,
    
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

--IDX_DEPARTAMENTOS_CLIENTE
CREATE INDEX IDX_DEPARTAMENTOS_CLIENTE ON DEPARTAMENTOS(ID_CLIENTE);
CREATE INDEX IDX_DEPARTAMENTOS_NOME ON DEPARTAMENTOS(NOME_DEPARTAMENTO);

COMMENT ON TABLE DEPARTAMENTOS IS 'Tabela que representa os departamentos vinculados a cada cliente.';

COMMENT ON COLUMN DEPARTAMENTOS.ID_DEPARTAMENTO    IS 'Código departamento.';
COMMENT ON COLUMN DEPARTAMENTOS.ID_CLIENTE         IS 'Código cliente.';
COMMENT ON COLUMN DEPARTAMENTOS.NOME_DEPARTAMENTO  IS 'Nome/Descrição do departamento.';