CREATE TABLE FATURAS_DE_CLIENTES (
    ID_FATURA_CLIENTE   NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CLIENTE          NUMBER NOT NULL,
    MES_REFERENCIA      VARCHAR2(7 BYTE) NOT NULL, -- Formato 'MM/YYYY'
    VALOR_TOTAL         NUMBER(12,2) DEFAULT 0,
    STATUS_PAGAMENTO    CHAR(2) DEFAULT 'EA' NOT NULL,

    CONSTRAINT FK_FATURA_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE),
    CONSTRAINT CHK_STATUS_PAGAMENTO CHECK (STATUS_PAGAMENTO IN ('EA', 'PG', 'VC'))
);

-- IDX_FATURAS_CLIENTE
CREATE INDEX IDX_FATURAS_CLIENTE    ON FATURAS_DE_CLIENTES(ID_CLIENTE);
CREATE INDEX IDX_FATURAS_MES        ON FATURAS_DE_CLIENTES(MES_REFERENCIA);

COMMENT ON TABLE FATURAS_DE_CLIENTES IS 'Tabela que armazena as faturas mensais consolidadas de cada cliente.';

COMMENT ON COLUMN FATURAS_DE_CLIENTES.ID_FATURA_CLIENTE     IS 'Código fatura.';
COMMENT ON COLUMN FATURAS_DE_CLIENTES.ID_CLIENTE            IS 'Código cliente.';
COMMENT ON COLUMN FATURAS_DE_CLIENTES.MES_REFERENCIA        IS 'Mês e ano de referência da fatura (ex: 08/2025).';
COMMENT ON COLUMN FATURAS_DE_CLIENTES.VALOR_TOTAL           IS 'Valor total de todas as transações no período.';
COMMENT ON COLUMN FATURAS_DE_CLIENTES.STATUS_PAGAMENTO      IS 'Situação da fatura: EA - Em Aberto, PG - Pago, VC - Vencido.';
