CREATE TABLE FATURAS_DE_ESTABELECIMENTOS (
    ID_FATURA_ESTAB     NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ESTABELECIMENTO  NUMBER NOT NULL,
    MES_REFERENCIA      VARCHAR2(7 BYTE) NOT NULL, -- Formato 'MM/YYYY'
    VALOR_TOTAL         NUMBER(12,2) DEFAULT 0,
    STATUS_REPASSE      CHAR(2) DEFAULT 'PD' NOT NULL,

    CONSTRAINT FK_FATURA_ESTAB FOREIGN KEY (ID_ESTABELECIMENTO) REFERENCES ESTABELECIMENTOS(ID_ESTABELECIMENTO),
    CONSTRAINT CHK_STATUS_REPASSE      CHECK (STATUS_REPASSE IN ('PD', 'PG', 'AT'))
);

--IDX_FATURAS_ESTAB
CREATE INDEX IDX_FATURAS_ESTAB      ON FATURAS_DE_ESTABELECIMENTOS(ID_ESTABELECIMENTO);
CREATE INDEX IDX_FATURAS_ESTAB_MES  ON FATURAS_DE_ESTABELECIMENTOS(MES_REFERENCIA);

COMMENT ON TABLE FATURAS_DE_ESTABELECIMENTOS IS 'Tabela de faturamento mensal dos estabelecimentos com base nas transações.';

COMMENT ON COLUMN FATURAS_DE_ESTABELECIMENTOS.ID_FATURA_ESTAB       IS 'Código da fatura do estabelecimento.';
COMMENT ON COLUMN FATURAS_DE_ESTABELECIMENTOS.ID_ESTABELECIMENTO    IS 'Código estabelecimento.';
COMMENT ON COLUMN FATURAS_DE_ESTABELECIMENTOS.MES_REFERENCIA        IS 'Mês e ano de referência da fatura (ex: 08/2025).';
COMMENT ON COLUMN FATURAS_DE_ESTABELECIMENTOS.VALOR_TOTAL           IS 'Valor total a ser repassado ao estabelecimento.';
COMMENT ON COLUMN FATURAS_DE_ESTABELECIMENTOS.STATUS_REPASSE        IS 'Status do repasse: PD - Pendente, PG - Pago, AT - Atrasado';