CREATE TABLE LOG_ALTERACAO_LIMITE (
    ID_LOG                NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CARTAO             NUMBER NOT NULL,
    LIMITE_ANTIGO         NUMBER(12,2),
    LIMITE_NOVO           NUMBER(12,2),
    DATA_ALTERACAO        DATE DEFAULT TO_DATE(TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'), 'DD/MM/YYYY HH24:MI:SS'),
    USUARIO_RESPONSAVEL   VARCHAR2(50 BYTE) NOT NULL,

    CONSTRAINT FK_LOG_LIMITE_CARTAO FOREIGN KEY (ID_CARTAO) REFERENCES CARTOES(ID_CARTAO)
);


CREATE INDEX IDX_LOG_CARTAO      ON LOG_ALTERACAO_LIMITE(ID_CARTAO);
CREATE INDEX IDX_LOG_DATA        ON LOG_ALTERACAO_LIMITE(DATA_ALTERACAO);
CREATE INDEX IDX_LOG_USUARIO     ON LOG_ALTERACAO_LIMITE(USUARIO_RESPONSAVEL);

COMMENT ON TABLE LOG_ALTERACAO_LIMITE IS 'Tabela de registro de alterações nos limites de crédito dos cartões.';

COMMENT ON COLUMN LOG_ALTERACAO_LIMITE.ID_LOG               IS 'Código de alteração.';
COMMENT ON COLUMN LOG_ALTERACAO_LIMITE.ID_CARTAO            IS 'Código do cartão.';
COMMENT ON COLUMN LOG_ALTERACAO_LIMITE.LIMITE_ANTIGO        IS 'Valor do limite de crédito antes da alteração.';
COMMENT ON COLUMN LOG_ALTERACAO_LIMITE.LIMITE_NOVO          IS 'Novo valor de limite de crédito definido.';
COMMENT ON COLUMN LOG_ALTERACAO_LIMITE.DATA_ALTERACAO       IS 'Data e hora da alteração do limite.';
COMMENT ON COLUMN LOG_ALTERACAO_LIMITE.USUARIO_RESPONSAVEL  IS 'Usuário responsável por realizar a alteração.';