CREATE TABLE TRANSACOES (
    ID_TRANSACAO         NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_CARTAO            NUMBER NOT NULL,
    ID_ESTABELECIMENTO   NUMBER NOT NULL,
    VALOR_TRANSACAO      NUMBER(12,2) NOT NULL,
    DATA_TRANSACAO       DATE DEFAULT TO_DATE(TO_CHAR(SYSDATE, 'DD/MM/YYYY HH24:MI:SS'), 'DD/MM/YYYY HH24:MI:SS'),
    STATUS_TRANSACAO     CHAR(1) DEFAULT 'P' NOT NULL,


    CONSTRAINT FK_TRANSACOES_CARTAO             FOREIGN KEY (ID_CARTAO) REFERENCES CARTOES(ID_CARTAO),
    CONSTRAINT FK_TRANSACOES_ESTABELECIMENTO    FOREIGN KEY (ID_ESTABELECIMENTO) REFERENCES ESTABELECIMENTOS(ID_ESTABELECIMENTO),
    CONSTRAINT CHK_STATUS_TRANSACAO             CHECK (STATUS_TRANSACAO IN ('A', 'P', 'N', 'C', 'E'))
);


CREATE INDEX IDX_TRANSACOES_CARTAO  ON TRANSACOES(ID_CARTAO);
CREATE INDEX IDX_TRANSACOES_ESTAB   ON TRANSACOES(ID_ESTABELECIMENTO);
CREATE INDEX IDX_TRANSACOES_DATA    ON TRANSACOES(DATA_TRANSACAO);

COMMENT ON TABLE TRANSACOES IS 'Tabela de registro das transações realizadas com os cartões emitidos.';

COMMENT ON COLUMN TRANSACOES.ID_TRANSACAO       IS 'Código da transação.';
COMMENT ON COLUMN TRANSACOES.ID_CARTAO          IS 'Código cartão.';
COMMENT ON COLUMN TRANSACOES.ID_ESTABELECIMENTO IS 'Código do estabelecimento.';
COMMENT ON COLUMN TRANSACOES.VALOR_TRANSACAO    IS 'Valor da transação.';
COMMENT ON COLUMN TRANSACOES.DATA_TRANSACAO     IS 'Data e hora da realização da transação.';
COMMENT ON COLUMN TRANSACOES.STATUS_TRANSACAO   IS 'Status da transação: A - Aprovada, P - Pendente, N - Negada, C - Cancelada, E - Estornada.';