SELECT
    E.NOME_FANTASIA,
    E.CNPJ,
    SUM(T.VALOR_TRANSACAO * E.TAXA_COMISSAO) AS VALOR_TOTAL_COMISSAO_DEVIDA
FROM
    ESTABELECIMENTOS E
JOIN
    TRANSACOES T ON E.ID_ESTABELECIMENTO = T.ID_ESTABELECIMENTO
WHERE
    T.STATUS_TRANSACAO = 'A' -- APROVADA
    AND TO_CHAR(T.DATA_HORA_TRANSACAO, 'MMYYYY') = '072025'
GROUP BY
    E.NOME_FANTASIA,
    E.CNPJ
ORDER BY
    VALOR_TOTAL_COMISSAO_DEVIDA DESC;