SELECT
    CLI.NOME_FANTASIA AS NOME_CLIENTE,
    SUBSTR(CAR.NUMERO_CARTAO_HASH, -4) AS ULTIMOS_4_DIGITOS_CARTAO,
    T.VALOR_TRANSACAO,
    T.DATA_TRANSACAO,
    T.STATUS_TRANSACAO,
    EST.NOME_FANTASIA AS NOME_ESTABELECIMENTO
FROM
    CLIENTES CLI
JOIN
    CARTOES CAR ON CLI.ID_CLIENTE = CAR.ID_CLIENTE
JOIN
    TRANSACOES T ON CAR.ID_CARTAO = T.ID_CARTAO
JOIN
    ESTABELECIMENTOS EST ON T.ID_ESTABELECIMENTO = EST.ID_ESTABELECIMENTO
WHERE
    CLI.ID_CLIENTE = 101 -- cModelo de cliente
ORDER BY
    T.DATA_HORA_TRANSACAO DESC;