SELECT
    C.ID_CARTAO,
    C.NUMERO_CARTAO_HASH,
    C.LIMITE_CREDITO,
    D.NOME_DEPARTAMENTO,
    MAX(C.LIMITE_CREDITO) OVER (PARTITION BY D.ID_DEPARTAMENTO) AS MAIOR_LIMITE_DEPARTAMENTO
FROM
    CARTOES C
JOIN
    DEPARTAMENTOS D ON C.ID_DEPARTAMENTO = D.ID_DEPARTAMENTO
ORDER BY
    D.NOME_DEPARTAMENTO, C.LIMITE_CREDITO DESC;