SELECT
    D.NOME_DEPARTAMENTO,
    SUM(T.VALOR_TRANSACAO) AS VOLUME_TOTAL_VENDAS
FROM
    DEPARTAMENTOS D
JOIN
    CARTOES C ON D.ID_DEPARTAMENTO = C.ID_DEPARTAMENTO
JOIN
    TRANSACOES T ON C.ID_CARTAO = T.ID_CARTAO
WHERE
    T.STATUS_TRANSACAO = 'A' -- APROVADA
    AND TRUNC(T.DATA_TRANSACAO, 'MM') = TRUNC(SYSDATE, 'MM') -- MÊS ATUAL
GROUP BY
    D.NOME_DEPARTAMENTO
ORDER BY
    VOLUME_TOTAL_VENDAS DESC
FETCH FIRST 3 ROWS ONLY;